### ISSUE TITLE
suppress warnings about deprecated fields and enum values

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-swift#212]
The source protos (or discovery docs) may have deprecated fields, enum values, enums, methods, or even full services.

We carry the deprecation annotations to the Swift code, so our customers can receive a warning if they use the deprecated things.

Our generated code also uses these values and fields, in case we receive them from the wire, or somebody uses them.

The latter usage produces warnings. I would like to suppress these warnings.

**Comment by coryan** [comment]
We could use this:

```
#if hasAttribute(diagnose)
@diagnose(DeprecatedDeclaration, as: warning, reason: "Use the new modern API instead.")
#endif
```

That would let us support 6.2, and silence the warnings for 6.4 and higher.  Our own builds will soon use 6.4,   so they could enable all warnings as errors. We would need to disable the `warnings-as-errors` for the builds using 6.2

**Comment by chingor13** [comment]
Additional severity context from the DX review (also related to #438):

Building a minimal executable depending on `swift-google-cloud-aiplatform-v1` + `swift-google-cloud-compute-v1` + `swift-google-cloud-kms-v1` emits **1,620 deprecation warnings** from the SDK's generated `Codable` switch statements (e.g., `'fieldValueOverriden' is deprecated` 600 times, `'rawKey'` and `'rsaEncryptedKey'` 100 times each).

More critically, this prevents any downstream consumer or CI build that uses `-warnings-as-errors` (`-Werror`) from compiling the SDK at all (failing immediately on `kms-v1`):

```text
generated/swift-google-cloud-kms-v1/Sources/GoogleCloudKMSV1/AccessReason.swift:162:56: error: 'modifiedCustomerInitiatedAccess' is deprecated [#DeprecatedDeclaration]
```

**Suggested direction:**
Prioritize fixing this before 1.0 by annotating the generated `Codable` serialization helper/switch methods with `@available(*, deprecated)` (or equivalent deprecation warning suppression) so deprecations remain visible on the public enum cases/properties where intended without failing `-warnings-as-errors` builds.

**Comment by coryan** [comment]
I think this is fixed. The build looks clean to me.
